### PR TITLE
feat(bytecode): `parseBytecode` into ABI

### PR DESCRIPTION
**Pull request by Raiden1411**
## Description

This PR aims to implement a way to parse smart contract bytecode into strongly typed abis.

The main goal is to have a 1:1 representation from typescript typesystem and the runtime implementation since the aim is not to outright create a disassembler in this PR.

## Additional Information

- [x] I read the [contributing guide](https://github.com/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md)
- [x] I added documentation related to the changes made.
- [x] I added or updated tests related to the changes made.

Your ENS/address:

---

## PR-Codex overview
This PR adds the ability to parse smart contract bytecode into ABIs. 

### Detailed summary
- Adds `parseBytecode` function to parse bytecode into strongly typed ABIs
- Adds `InvalidBytecodeError` error class
- Updates various files to support bytecode parsing and `InvalidBytecodeError`
- Includes tests and type definitions

> The following files were skipped due to too many changes: `src/bytecode/types/utils.test-d.ts`, `src/bytecode/types/utils.ts`, `src/bytecode/types/opcodes.ts`, `docs/api/bytecode.md`, `src/bytecode/runtime/selectors.ts`, `src/bytecode/runtime/selectors.test.ts`, `src/bytecode/types/bytecode.ts`, `src/bytecode/types/config.ts`, `src/bytecode/runtime/defaults.ts`, `src/bytecode/parseBytecode.test-d.ts`, `src/bytecode/types/bytecode.test-d.ts`, `src/bytecode/__snapshots__/parseBytecode.test.ts.snap`, `src/test/bytecodes.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by tmm** [comment]
This is wild! Let me know when it's ready to check out more. We'll want to figure out the best way to package this up for users too.

**Comment by Raiden1411** [comment]
By next week i should have this more polished and ready for a proper review. Trying to figure out the best way to approach this so that we can avoid using 3rd party apis to resolve the selectors. Want to implement something like you suggested so that folks can use and extends both the runtime and type config. But having some difficulty finding a api that lets you easily export by most common and selector type.

**Comment by Raiden1411** [comment]
@tmm this is ready for a proper review. Let me know what you think, also feel free to change anything as you see fit.

**Comment by tmm** [comment]
@Raiden1411 awesome! will take a look.

**Comment by roninjin10** [comment]
wtf this is possible?!?!

**Comment by Raiden1411** [comment]
Yeah this one is not as powerfull as heimdall or whatsabi since we try to infer the selectors at the type level and try to have a 1-1 representation of runtime with the resulting types.

**Comment by Raiden1411** [comment]
@tmm considering closing this one. Might be to niche of a feature and also might ask to much of a  consumer to setup. What do you think?

**Comment by Raiden1411** [comment]
Closing this one. Might revisit in the future if the feature makes more sense then.

**Pull request closed without merging**
