### PR TITLE
Feat: Add support for Human Readable Abi

### PR DESCRIPTION
**Pull request by Raiden1411**
## Description

This PR aims to add support for Human Readable Abis in ABIType.

The scope of this is just for [ethers](https://docs.ethers.org/v5/api/utils/abi/formats/#abi-formats--human-readable-abi).
This can infer almost everything from the Human Readable Abi with the exception of nested named and array tuples.
More details of it working are shown in the readme and also on the habi.test-d.ts files.

I am creating this PR as draft to serve the purpose of discussion and general improvements to the code. As i though in having the code already would lead to a more productive discussion and wouldn't mind in case this gets rejected.

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: 0x75EF32C862b8fe2915D49b38a2AECc8744622864

### CODE REVIEW

**Comment by Raiden1411** [comment]
Nested tuples current max without breaking inference is 10 deep. I think this is enough depth for pretty much all use cases

**Comment by tmm** [comment]
Pretty cool to see this work being done! I started going down a similar path [here](https://github.com/wagmi-dev/abitype/blob/tmm/human-readable-abi/src/examples/humanReadable.ts). Will check it out.

**Comment by Raiden1411** [comment]
Oh i didn't notice it. Could have save me some time if i did.

In this version i tried to match ethersjs as much as possible. This could possible be extended to support  keywords like `external`, `public`, `memory`, `storage` and `calldata` to try and mimic solidity interfaces as much as possible but Structs kinda break this inference so i decided to opt out of these key words and since ethers already drops them internally if you add them i though it made sense in not adding them. But let me know your thoughts

**Comment by tmm** [comment]
Sweet! Been a busy week. Excited to dig in soon.

> unless you want to add support to the things i pointed in the previous comment

Will think about this some more too.

**Comment by Raiden1411** [comment]
No problem! Exciting week for wagmi. Great work on the cli tool!

**Comment by Raiden1411** [comment]
I had tried the idea of `isUnknown` before the previous commit but I was taking the wrong approach. This works the same as the previous commit and doesn't require the change to eslint's banned types. Also was using `Exclude` instead of `Extract` and that's why my previous approaches weren't working as I hoped.

**Pull request merged**
