### PR TITLE
docs: adds shiki-twoslash

### PR DESCRIPTION
**Pull request by Raiden1411**
- Initial setup
- Integrates twoslash

## Description

This PR aims to add integration of shiki-twoslash to the docs website.
Opening this as a draft because it is still in a early stage.

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:0x75EF32C862b8fe2915D49b38a2AECc8744622864

### CODE REVIEW

**Comment by tmm** [comment]
twoslash in the docs would be amazing! Might be worthwhile to create a standalone package for VitePress too and use that here (there's a [Vuepress twoslash package](https://github.com/shikijs/twoslash/tree/main/packages))

**Comment by Raiden1411** [comment]
Once the integration here is completed, I could work on doing something similar to [viem](https://github.com/wagmi-dev/viem)

**Comment by Raiden1411** [comment]
I already have some of it working. Something things are broken like code-groups and the lsp integration.
Still figuring those ones out. And yes might be a good idea to do that too

**Comment by Raiden1411** [comment]
Had to convert the docs package to a module to make this work though as using cjs the website never ran with the markdown-it package

**Comment by Raiden1411** [comment]
Also might be usefull to take a look at this [ts-twoslasher](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/ts-twoslasher)

**Comment by Raiden1411** [comment]
@tmm hopefully if this [PR](https://github.com/vuejs/vitepress/pull/2059) lands it will fix the problem that I was having with the code-groups. Otherwise we might need to create a custom component or something.

**Comment by Raiden1411** [comment]
@tmm the integration of twoslash should be completed. I had to add the shiki dependency so that the the `bash` and some "hacking" to have the pre tags associated with it display like they do currently. The problem here is that `twoslash-shiki` is using `shiki` 0.10.1. Also inserted the previously discussed fix for the code-groups so that we don't have to wait for the fix to get merged (if ever).

We wait can wait for those dependencies to get fix (will also create something on `twoslash-shiki` to ask to update their `shiki` dependency to the latest version or we can always update these dependencies later and remove the "bandages" here.

Let me know what you think or if there is anything that you want to add.

**Comment by Raiden1411** [comment]
Vitepress PR got merged :)

**Pull request merged**
