### PR TITLE
fix: bug fixes on `splitParameters` and `parseAbiParameter`

### PR DESCRIPTION
**Pull request by Raiden1411**
## Description

Set of changes that didn't make it in time of #93

- Fixes a bug where `splitParameters` was incorrectly parsing tuples with too many closing or opening parenthesis.
- Fixes a bug where invalid modifiers where being parsed on `error`, `struct`, and `event` signatures.
- Fixes a bug where it was possible to parse protected `Solidity` keywords.
- Fixes a bug where you could use `calldata`, `memory`, and `storage` on non array types. (`strings` and `bytes` are treated as array type in solidity).

This PR also has a change on `modifiers` to use a `Set` instead of an `Array` (mostly trying to not hurt performance as much from the above changes).

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:0x75EF32C862b8fe2915D49b38a2AECc8744622864

### CODE REVIEW

**Comment by Raiden1411** [comment]
@tmm was working on this in #93 but didn't manage it to commit in time.

Also the result of the tests of the cache key being by modifier were in vain because it would leak on signatures that wouldn't allow it (e.g. error and others).

Also doing any form of "sanitazation" on the cache key would end up hurting performance by a lot. So leaving it by type seems to be the fastest and safest option.

**Comment by tmm** [comment]
Sounds good! Sorry I merged in #93 preemptively. You can mark a PR as a draft if there are still things you want to do and I'll be better about asking before I merge.

**Comment by Raiden1411** [comment]
Don't need to apologize! There was no way for you to know. And yes next time i will do that.
For this one you can go ahead and review it safely.

**Review by tmm — COMMENTED** [review]
Made a few updates. Overall, really solid.

Would be nice to get some of this over to the type-level side (e.g. protected keyword validation).

**Comment by Raiden1411** [comment]
Will look into adding those at the type level. Would it make sense in adding these in #95? Since its already doing some of the type level validation regarding the parameters

Let me know what you think

**Comment by tmm** [comment]
Sounds good! If you're happy with this PR as-is, the looks ready to go.

**Comment by Raiden1411** [comment]
Yep you can go ahead and merge!

**Review by tmm — APPROVED** [review]

**Pull request merged**
